import {project as P} from './data.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const statusTag=s=>`<span class="tag ${s}">${esc(P.statuses[s]||s)}</span>`;
const slug=s=>s.toLowerCase().replace(/[^a-zа-я0-9]+/gi,'-').replace(/^-|-$/g,'');
const nav=['О проекте','Планы','Электрика','Освещение','Сантехника','Развёртки','Мебель','Материалы','Спецификации','Комплектация','Бюджет','3D','Визуализации','Проверки','Источники'];
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function point(x,y,id,type){return `<g class="layer-${type}" data-inspect="${id}" transform="translate(${x} ${y})"><circle class="point-${type}" r="92"/><text class="idlabel" x="110" y="35">${id}</text></g>`}
function planSvg(){
 const shell=P.shell.map(p=>p.join(',')).join(' ');
 const parts=P.partitions.map(p=>`<rect class="partition layer-partitions" x="${p[1]}" y="${p[2]}" width="${p[3]}" height="${p[4]}" transform="rotate(${p[5]} ${p[1]} ${p[2]})" data-inspect="${p[0]}"/>`).join('');
 const furn=[['F10',5800,1300,600,2000],['F01',1275,5800,1700,2100],['F02',150,4800,1800,600],['F04',4850,4400,1000,2100],['F05',3745,6620,1400,600],['F06',4960,3720,1390,600],['BATH-TUB',3970,110,750,1700],['WC',2460,40,700,700],['WASHER',3210,40,650,650],['BASIN',2440,1420,650,500],['FRIDGE',1670,0,650,650],['KITCHEN',0,0,600,1800],['DINING',0,1950,1100,650],['F07',1250,3350,1600,800],['F08',0,3200,250,950]].map(a=>`<rect class="furn layer-furniture" x="${a[1]}" y="${a[2]}" width="${a[3]}" height="${a[4]}" rx="30" data-inspect="${a[0]}"/>`).join('');
 const rooms=`<text class="roomlabel layer-labels" x="850" y="6200">СПАЛЬНЯ · 11.24</text><text class="roomlabel layer-labels" x="4100" y="6000">ВТОРАЯ · 11.32</text><text class="roomlabel layer-labels" x="2680" y="1100">ВАННАЯ · 4.38</text><text class="roomlabel layer-labels" x="700" y="3000">КУХНЯ–ГОСТИНАЯ</text>`;
 const e=[['E02',6200,1250],['E04',2050,780],['E05',550,1500],['E09',1000,800],['E13',350,3600],['E15',350,3850],['E18',2900,5750],['E19',2900,7850],['E24',4300,6900],['E25',4550,6900],['E29',2500,1550],['E30',3400,850],['E32',4650,1500]].map(a=>point(a[1],a[2],a[0],'e')).join('');
 const p=[['P01',700,650],['P03',500,1000],['P04',500,1500],['P05',2700,1550],['P08',2600,500],['P10',4450,900],['P12',3500,650]].map(a=>point(a[1],a[2],a[0],'p')).join('');
 const l=[['L01',1200,1200],['L03',550,2350],['L04',1100,3700],['L06',1650,6500],['L09',5000,5700],['L11',3550,950],['L13',5400,2500]].map(a=>point(a[1],a[2],a[0],'l')).join('');
 return `<svg class="plan" viewBox="-700 -650 7800 9800" role="img" aria-label="Интерактивный план Variant D"><g id="zoom-root"><polygon class="shell" points="${shell}"/>${parts}${furn}${rooms}${e}${p}${l}<path class="dim layer-dimensions" d="M0 -260 H6400 M-260 0 V8300"/><text class="idlabel layer-dimensions" x="2700" y="-350">6400 мм · ТРЕБУЕТ ОБМЕРА</text><text class="idlabel layer-dimensions" transform="translate(-390 4400) rotate(-90)">≈8300 мм · ТРЕБУЕТ ОБМЕРА</text></g></svg>`;
}
function planCard(){return `<div class="sheet"><div class="sheet-title"><h3>Интерактивный план Variant D</h3><span class="sheet-no">MODEL / D</span></div><div class="plan-toolbar">${['partitions:Перегородки','furniture:Мебель','labels:Названия','e:Электрика','p:Сантехника','l:Свет','dimensions:Размеры'].map(x=>{let [k,v]=x.split(':');return `<label><input type="checkbox" data-layer="${k}" checked> ${v}</label>`}).join('')}<button id="reset-plan">Сбросить вид</button></div><div class="plan-wrap">${planSvg()}<div class="inspector" id="inspector"></div><div class="hint">Колесо — масштаб · drag — панорама · клик — данные</div></div></div>`}
function budgetBlock(){return `<div class="budget-controls"><button data-scenario="0">ЭКОНОМ</button><button data-scenario="1" class="active">ОПТИМАЛЬНЫЙ</button><button data-scenario="2">КОМФОРТ</button><button data-works="1" class="active">С РАБОТАМИ</button><button data-works="0">БЕЗ РАБОТ</button><button data-reserve="10">РЕЗЕРВ 10%</button><button data-reserve="15" class="active">РЕЗЕРВ 15%</button></div><div id="budget-summary"></div><div id="budget-table"></div>`}
function render(){
 $('#project-app').innerHTML=`<div class="app"><aside class="side"><div class="brand">ЛЕСНАЯ ПОЛЯНА<small>Цифровой рабочий альбом</small></div><div class="project-chip"><b>${P.meta.variant}</b><span>${P.meta.stage}</span></div><nav class="nav">${nav.map(n=>`<button data-go="${slug(n)}">${n}</button>`).join('')}</nav><div class="side-actions"><a href="model.html">3D модель ↗</a><button onclick="window.print()">PDF / печать</button></div></aside><main class="main"><div class="topbar"><button class="mobile-menu" id="mobile-nav">☰</button><div class="grow"><b>${P.meta.title}</b></div><div class="mode"><button data-view="album" class="active">ЧЕРТЁЖ</button><button data-view="work">РАБОЧИЙ АЛЬБОМ</button><button onclick="location.href='model.html'">3D</button><button data-go="визуализации">ВИЗУАЛИЗАЦИЯ</button></div><div class="statuslegend">${statusTag('project')}${statusTag('measure')}</div></div><div class="content">
<section id="о-проекте"><div class="hero"><div class="card"><div class="eyebrow">${P.meta.stage}</div><h1>Лиза.<br>Дизайн для реализации.</h1><p class="lead">Тёплый минимализм + soft Scandinavian + natural contemporary. Две отдельные комнаты, встроенное хранение, компактная кухня-гостиная и ванная без декоративной херни ради картинки.</p><div class="meta-grid"><div class="metric"><b>${P.meta.area.toFixed(3)} м²</b><span>контур условной модели</span></div><div class="metric"><b>${P.meta.ceiling} мм</b><span>проектная высота потолков</span></div><div class="metric"><b>${P.meta.region}</b><span>регион комплектации и работ</span></div><div class="metric"><b>${P.meta.date}</b><span>версия цен / ${P.meta.version}</span></div></div></div><div class="card"><div class="eyebrow">ПАЛИТРА</div><div class="palette">${P.palette.map(s=>`<div class="swatch"><i style="background:${s[1]}"></i>${s[0]}</div>`).join('')}</div><div class="note warning" style="margin-top:18px"><b>Критично</b><br>Стояки, канализация, вентшахты, несущие стены, радиаторы, трассы кондиционеров и существующая электрика не выдуманы. Где данных нет — стоит статус инженерной проверки.</div></div></div></section>
<section id="планы"><div class="section-head"><div><div class="eyebrow">01–31</div><h2>Планы и рабочая логика</h2></div><p>Одна геометрическая база, разные технические слои. Variant D сохранён как основной.</p></div>${planCard()}<div class="sheet"><div class="sheet-title"><h3>Экспликация помещений</h3><span class="sheet-no">07</span></div>${table(['Помещение','Площадь','Статус','Примечание'],P.rooms.map(r=>[r.name,`${r.area.toFixed(3)} м²`,statusTag(r.status),r.note]))}</div><div class="sheet"><div class="sheet-title"><h3>Содержание рабочего альбома</h3><span class="sheet-no">02</span></div><div class="sheet-index">${P.sheets.map((s,i)=>`<button>${String(i+1).padStart(2,'0')} · ${s.replace(/^\d+\s/,'')}</button>`).join('')}</div></div></section>
<section id="электрика"><div class="section-head"><div><div class="eyebrow">25–27</div><h2>Электрика</h2></div><p>Точки — проектные, с ID и высотами. Кабели, автоматы и защиты рассчитываются электриком после данных по щиту и мощности.</p></div><div class="sheet">${table(['ID','Помещение','Тип','Высота, мм','Назначение','Кол-во','Комментарий'],P.electrical.map(r=>r.map(esc)))}</div></section>
<section id="освещение"><div class="section-head"><div><div class="eyebrow">21–24</div><h2>Освещение</h2></div><p>2700–3000K, CRI ≥90 где доступно; без шахматки из спотов.</p></div><div class="grid"><div class="sheet span-8">${table(['ID','Зона','Тип','CCT','CRI','Кол-во','Статус'],P.lights)}</div><div class="sheet span-4">${table(['Сценарий','Группы','Логика'],P.lightingScenes)}</div></div><div class="sheet"><h3>Ведомость светильников · реальные модели</h3>${table(['ID','Модель','Мощность','CCT','CRI','Размер','Кол-во','Цена','Итого','Источник'],P.luminaireProducts.map(x=>[x.id,x.model,x.power,x.cct,x.cri,x.size,x.qty,money(x.price),money(x.price*x.qty),`<a class="source-link" href="${x.url}" target="_blank">${x.store} ↗</a><br><small>${x.note}</small>`]))}</div></section>
<section id="сантехника"><div class="section-head"><div><div class="eyebrow">28–31</div><h2>Сантехника и инженерия</h2></div><p>Оборудование расставлено, но трассы не придуманы: все выводы предварительные до стояков и уклонов.</p></div><div class="sheet">${table(['ID','Помещение','Сеть','Высота, мм','Назначение','Статус'],P.plumbing.map(r=>[...r.slice(0,5),statusTag('engineering')]))}</div><div class="sheet"><div class="note warning">Вентиляция и кондиционирование: требования и зоны оборудования показаны, фальшивых трасс нет. ${P.engineering[1]} ${P.engineering[2]}</div></div></section>
<section id="развёртки"><div class="section-head"><div><div class="eyebrow">32–38</div><h2>Развёртки и раскладки</h2></div><p>Проектные фронты 2700 мм. Чистовые привязки — после выравнивания стен и контрольного обмера.</p></div><div class="grid"><div class="sheet span-6"><div class="sheet-title"><h3>Кухня · фронтальный вид</h3><span class="sheet-no">32</span></div><div class="elevation"><div class="floor"></div><div class="cab" style="left:5%;width:12%;height:44%"></div><div class="cab" style="left:17%;width:12%;height:44%"></div><div class="cab" style="left:29%;width:10%;height:44%"></div><div class="cab" style="left:39%;width:12%;height:44%"></div><div class="cab" style="left:51%;width:12%;height:44%"></div><div class="cab" style="left:63%;width:14%;height:78%"></div><div class="upper" style="left:5%;width:58%;height:28%"></div><div class="label" style="left:5%;top:44%">столешница h=900</div></div>${table(['ID','Модуль','Ширина','Примечание'],P.kitchenModules)}</div><div class="sheet span-6"><div class="sheet-title"><h3>Ванная · 4 стены</h3><span class="sheet-no">33 / 38</span></div><div class="elevation"><div class="floor"></div><div class="cab" style="left:8%;width:28%;height:26%"></div><div class="upper" style="left:8%;width:28%;height:28%"></div><div class="cab" style="right:8%;width:34%;height:22%"></div><div class="label" style="left:8%;top:18%">зеркало 650</div><div class="label" style="right:8%;bottom:34%">ванна 1700×750</div></div><p class="note">Плитка: крупный спокойный формат 600×1200 либо близкий; старт от видовых осей, подрезки у внутренних углов/за ванной. Финальная раскладка после чистовых размеров.</p></div></div></section>
<section id="мебель"><div class="section-head"><div><div class="eyebrow">39–45</div><h2>Мебель и столярка</h2></div><p>Встроенные шкафы до потолка. Производственные размеры — только после чистовых замеров.</p></div><div class="sheet">${table(['ID','Помещение','Предмет','Размер','Тип','Статус'],P.furniture.map(f=>[f.id,f.room,f.item,f.size,f.type,statusTag(f.status)]))}</div><div class="sheet">${table(['ID','Изделие','Габарит','Наполнение','Примечание'],P.joinery.map(j=>[j.id,j.name,j.size,j.inside,j.note]))}</div><div class="sheet"><h3>Узлы</h3>${table(['ID','Узел','Решение'],P.nodes)}</div></section>
<section id="материалы"><div class="section-head"><div><div class="eyebrow">КОМПЛЕКТАЦИЯ</div><h2>Отделка и реальные товары</h2></div><p>Приоритет — Лемана ПРО Кемерово. Цена динамическая: дата проверки хранится у каждой позиции.</p></div><div class="sheet">${table(['Помещение','Поверхность','Материал','Цвет','Площадь/объём','Статус'],P.finishes)}</div><div class="sheet">${table(['ID','Материал','Бренд','Артикул','Цена','Кол-во','Источник/метод'],P.buildMaterials.map(x=>[x.id,x.name,x.brand,x.sku,x.price?money(x.price):'требует повторной проверки',x.qty??'по обмеру',`<a class="source-link" href="${x.source}" target="_blank">источник ↗</a><br>${esc(x.consumption)}`]))}</div></section>
<section id="спецификации"><div class="section-head"><div><div class="eyebrow">ОБЩАЯ ТАБЛИЦА</div><h2>Спецификации</h2></div><p>Реальные карточки, артикулы и текущие ориентиры цен; статус показывает уровень уверенности.</p></div><div class="sheet"><div class="procure-summary"><b>Текущая корзина: ${money(P.products.reduce((s,x)=>s+x.price*x.qty,0))}</b><span>${P.products.length} позиций · RUB</span></div>${table(['ID','Категория','Предмет','Бренд','Артикул','Ед.','Кол-во','Цена','Итого','Магазин','Статус','Ссылка'],P.products.map(x=>[x.id,x.cat,x.name,x.brand,x.sku,x.unit,x.qty,money(x.price),money(x.price*x.qty),x.store,statusTag(x.status),`<a class="source-link" href="${x.url}" target="_blank">карточка ↗</a><br><small>${x.checked}</small>`]))}</div></section>
<section id="комплектация"><div class="section-head"><div><div class="eyebrow">ЗАКУПКА</div><h2>Комплектация</h2></div><p>Что купить, сколько, где и чем заменить. Срок — только когда опубликован, иначе «уточнить».</p></div><div class="sheet"><div class="procure-summary"><b>Лемана ПРО Кемерово · позиции: ${money(P.products.filter(x=>x.store.includes('Лемана')).reduce((s,x)=>s+x.price*x.qty,0))}</b><span>без непроверенных черновых объёмов</span></div>${table(['ID','Что купить','Кол-во','Магазин','Цена','Срок','Статус/замена'],P.products.map(x=>[x.id,x.name,`${x.qty} ${x.unit}`,x.store,money(x.price),'уточнить перед заказом',`${statusTag(x.status)}<br><small>${esc(x.note||'аналог по габариту и функции')}</small>`]))}</div></section>
<section id="бюджет"><div class="section-head"><div><div class="eyebrow">КЕМЕРОВО · 18.09.2026</div><h2>Dashboard бюджета</h2></div><p>Три сценария, переключатель работ и резерв 10/15%.</p></div><div class="sheet">${budgetBlock()}</div><div class="sheet"><h3>Стоимость работ · рыночная вилка</h3>${table(['Работа','Ед.','Минимум','Типично','Верх','Источник'],P.workRates.map(r=>[r[0],r[1],money(r[2]),money(r[3]),money(r[4]),`<a class="source-link" href="${r[6]}" target="_blank">${r[5]} ↗</a>`]))}</div></section>
<section id="3d"><div class="section-head"><div><div class="eyebrow">СОХРАНЕНО</div><h2>3D-модель</h2></div><p>Исходная Three.js-модель и геометрия не удалены.</p></div><div class="sheet"><a class="source-link" href="model.html">Открыть полноценный 3D-режим Variant D →</a></div></section>
<section id="визуализации"><div class="section-head"><div><div class="eyebrow">ПРОЕКТНЫЕ КАДРЫ</div><h2>Визуализации</h2></div><p>Геометрически связанные проектные кадры-борды; не выдаём фотогенерацию за финальный render до обмера.</p></div><div class="visual-grid">${P.visuals.map(v=>`<div class="visual"><span>${v[0]} · ${v[1]}</span><small>${v[2]}</small></div>`).join('')}</div></section>
<section id="проверки"><div class="section-head"><div><div class="eyebrow">QA</div><h2>Проверки и конфликты</h2></div><p>Исправленное отделено от открытых инженерных вопросов.</p></div><div class="sheet"><div class="checks">${P.conflicts.map(c=>`<div class="check"><b>${c[0]}</b><div><b>${c[1]}</b><br><small>${c[3]}</small></div><span class="pill ${c[2]==='исправлено'?'fixed':c[2]==='предупреждение'?'warn':'open'}">${c[2]}</span></div>`).join('')}</div></div><div class="grid"><div class="sheet span-6"><h3>Обязательно перемерить</h3><ol>${P.measurement.map(x=>`<li>${x}</li>`).join('')}</ol></div><div class="sheet span-6"><h3>Инженерные вопросы</h3><ol>${P.engineering.map(x=>`<li>${x}</li>`).join('')}</ol></div></div></section>
<section id="источники"><div class="section-head"><div><div class="eyebrow">МЕТОДИКА</div><h2>Источники и методика</h2></div><p>У товара хранится регион/дата/ссылка. Проектные объёмы отделены от данных, требующих обмера.</p></div><div class="sheet">${table(['Что','Источник','Дата','Ссылка'],P.sources.map(s=>[s[0],s[1],s[2],`<a class="source-link" href="${s[3]}" target="_blank">${s[3]} ↗</a>`]))}<div class="note warning" style="margin-top:14px">Цена и наличие могут измениться; перед заказом обязательна повторная проверка корзины в регионе Кемерово.</div></div></section>
</div></main></div>`;
 bind(); updateBudget();
}
function bind(){
 $('#mobile-nav')?.addEventListener('click',()=>$('.side')?.classList.toggle('open'));
 $$('[data-go]').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'});$('.side')?.classList.remove('open')});
 $$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.body.classList.toggle('work-mode',b.dataset.view==='work');if(b.dataset.view==='work')document.getElementById('планы').scrollIntoView()});
 $$('[data-layer]').forEach(c=>c.onchange=()=>$$(`.layer-${c.dataset.layer}`).forEach(x=>x.classList.toggle('hidden-layer',!c.checked)));
 setupPlan();
 $$('[data-scenario]').forEach(b=>b.onclick=()=>{budgetState.scenario=+b.dataset.scenario;$$('[data-scenario]').forEach(x=>x.classList.toggle('active',x===b));updateBudget()});
 $$('[data-works]').forEach(b=>b.onclick=()=>{budgetState.works=+b.dataset.works;$$('[data-works]').forEach(x=>x.classList.toggle('active',x===b));updateBudget()});
 $$('[data-reserve]').forEach(b=>b.onclick=()=>{budgetState.reserve=+b.dataset.reserve;$$('[data-reserve]').forEach(x=>x.classList.toggle('active',x===b));updateBudget()});
}
const budgetState={scenario:1,works:1,reserve:15};
function updateBudget(){
 let rows=P.budget.filter(r=>budgetState.works||r[4]!=='works'),base=rows.reduce((s,r)=>s+r[1+budgetState.scenario],0),reserve=base*budgetState.reserve/100,total=base+reserve;
 let group={materials:0,works:0,furniture:0,appliances:0,sanitary:0,kitchen:0,light:0,other:0};rows.forEach(r=>{let k=group[r[4]]!==undefined?r[4]:'other';group[k]+=r[1+budgetState.scenario]});
 $('#budget-summary').innerHTML=`<div class="budget-total"><div class="metric"><b>${money(total)}</b><span>ИТОГО +${budgetState.reserve}% резерв</span></div><div class="metric"><b>${money(base)}</b><span>до резерва</span></div><div class="metric"><b>${money(reserve)}</b><span>резерв</span></div><div class="metric"><b>${money(group.works)}</b><span>работы</span></div></div><div class="grid"><div class="span-4 note">Материалы и отделка: <b>${money(group.materials)}</b></div><div class="span-4 note">Мебель + кухня: <b>${money(group.furniture+group.kitchen)}</b></div><div class="span-4 note">Техника + сантехника + свет: <b>${money(group.appliances+group.sanitary+group.light)}</b></div></div>`;
 $('#budget-table').innerHTML=table(['Раздел','Сумма','Доля'],rows.map(r=>{let v=r[1+budgetState.scenario];return[r[0],money(v),`<div class="bar"><i style="width:${Math.max(2,v/base*100)}%"></i></div>${(v/base*100).toFixed(1)}%`]}).concat([['Резерв',money(reserve),`${budgetState.reserve}%`]]));
}
function setupPlan(){
 const svg=$('.plan'),root=$('#zoom-root'),inspector=$('#inspector');if(!svg||!root)return;let scale=1,tx=0,ty=0,drag=false,last=[0,0];const apply=()=>root.setAttribute('transform',`translate(${tx} ${ty}) scale(${scale})`);
 svg.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(3,Math.max(.55,scale*(e.deltaY<0?1.1:.9)));apply()},{passive:false});
 svg.addEventListener('pointerdown',e=>{drag=true;last=[e.clientX,e.clientY];svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;tx+=(e.clientX-last[0])*7/scale;ty+=(e.clientY-last[1])*7/scale;last=[e.clientX,e.clientY];apply()});svg.addEventListener('pointerup',()=>drag=false);
 svg.addEventListener('click',e=>{let g=e.target.closest('[data-inspect]');if(!g)return;let id=g.dataset.inspect,found=P.electrical.find(x=>x[0]===id)||P.plumbing.find(x=>x[0]===id)||P.furniture.find(x=>x.id===id)||P.partitions.find(x=>x[0]===id);inspector.classList.add('open');inspector.innerHTML=`<b>${id}</b><small>${esc(found?JSON.stringify(found).replace(/[\[\]{}\"]/g,' '):'Проектный элемент')}</small><br><button onclick="this.parentNode.classList.remove('open')">Закрыть</button>`});
 $('#reset-plan')?.addEventListener('click',()=>{scale=1;tx=0;ty=0;apply()});
}
render();
