import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mm} from '../data/model.js';
import {moveWithCollision,canStand} from './collision.js';
export class Cameras{
 constructor(canvas,geometry,getObstacles,onChange){this.canvas=canvas;this.geometry=geometry;this.getObstacles=getObstacles;this.onChange=onChange;this.perspective=new THREE.PerspectiveCamera(50,1,.03,100);this.ortho=new THREE.OrthographicCamera(-6,6,6,-6,.03,100);this.camera=this.ortho;this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.maxPolarAngle=Math.PI*.49;this.controls.minDistance=1;this.controls.maxDistance=25;this.controls.minZoom=.4;this.controls.maxZoom=5;this.keys=new Set();this.eye=1700;this.yaw=Math.PI;this.pitch=0;this.mode='iso';this.drag=null;this.route=null;
 window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape'].includes(e.code)){if(this.mode==='walk')e.preventDefault();this.keys.add(e.code);if(e.code==='Escape'){this.route=null;document.exitPointerLock?.();}}});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.keys.clear());
 canvas.addEventListener('pointerdown',e=>{if(this.mode==='walk'){this.drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId);}});canvas.addEventListener('pointerup',()=>this.drag=null);canvas.addEventListener('pointermove',e=>{if(this.mode!=='walk')return;if(document.pointerLockElement===canvas||this.drag){const dx=document.pointerLockElement===canvas?e.movementX:e.clientX-this.drag.x,dy=document.pointerLockElement===canvas?e.movementY:e.clientY-this.drag.y;this.yaw-=dx*.003;this.pitch=Math.max(-1.4,Math.min(1.4,this.pitch-dy*.003));if(this.drag)this.drag={x:e.clientX,y:e.clientY};}});canvas.addEventListener('dblclick',()=>{if(this.mode==='walk')canvas.requestPointerLock?.().catch?.(()=>{});});this.setMode('iso');}
 resize(w,h){this.aspect=w/h;this.perspective.aspect=this.aspect;this.perspective.updateProjectionMatrix();const half=Math.max(5.5,(this.mode==='plan'?3.9:5.8)/this.aspect);this.ortho.left=-half*this.aspect;this.ortho.right=half*this.aspect;this.ortho.top=half;this.ortho.bottom=-half;this.ortho.updateProjectionMatrix();}
 setMode(mode){this.mode=mode;this.route=null;this.controls.dispose();const ortho=['iso','plan'].includes(mode);this.camera=ortho?this.ortho:this.perspective;this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.maxPolarAngle=Math.PI*.49;this.controls.minDistance=1;this.controls.maxDistance=25;this.controls.minZoom=.4;this.controls.maxZoom=5;this.controls.target.set(3.2,0,4.15);this.camera.up.set(0,1,0);this.camera.zoom=1;
 if(mode==='walk'){this.controls.enabled=false;this.camera.position.set(5.95,mm(this.eye),.85);this.yaw=Math.PI;this.pitch=0;}
 else if(mode==='plan'||mode==='top'){this.camera.position.set(3.2,mode==='top'?14:15,4.151);this.camera.up.set(0,0,-1);this.controls.enableRotate=false;}
 else if(mode==='perspective'){this.camera.position.set(10,9,13);}
 else{this.camera.position.set(13.2,10,14.15);}
 this.camera.lookAt(this.controls.target);if(this.aspect)this.resize(this.canvas.clientWidth,this.canvas.clientHeight);this.camera.updateProjectionMatrix();this.controls.update();this.onChange?.();}
 setEye(v){this.eye=v;if(this.mode==='walk')this.camera.position.y=mm(v);}
 teleport(point,target){let p=point;if(!canStand(...p,this.geometry,this.getObstacles(),250))return false;this.camera.position.set(mm(p[0]),mm(this.eye),mm(p[1]));if(target){this.yaw=Math.atan2(-(target[0]-p[0]),-(target[1]-p[1]));this.pitch=-.06;}this.route=null;return true;}
 view(position,target,ortho=false){this.setMode(ortho?'iso':'perspective');this.camera.position.set(...position);this.controls.target.set(...target);this.camera.lookAt(...target);this.controls.update();}
 tick(dt){if(this.mode!=='walk'){this.controls.update();return;}
 let dx=0,dy=0;const speed=1150,delta=Math.min(dt,.05);let moving=this.keys.size>0;if(moving)this.route=null;
 if(this.route?.length){const [tx,ty]=this.route[0];const px=this.camera.position.x*1000,py=this.camera.position.z*1000;const dist=Math.hypot(tx-px,ty-py);if(dist<40)this.route.shift();else{dx=(tx-px)/dist*speed*delta;dy=(ty-py)/dist*speed*delta;const target=Math.atan2(-dx,-dy);const diff=Math.atan2(Math.sin(target-this.yaw),Math.cos(target-this.yaw));this.yaw+=diff*Math.min(1,delta*7);}}
 else{let forward=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0),right=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);const norm=Math.hypot(forward,right)||1;dx=(-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*right)/norm*speed*delta;dy=(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*right)/norm*speed*delta;}
 const p=moveWithCollision({x:this.camera.position.x*1000,y:this.camera.position.z*1000},dx,dy,this.geometry,this.getObstacles(),250);this.camera.position.set(mm(p.x),mm(this.eye),mm(p.y));this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);}
}
