import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-webgl','--single-process','--no-zygote']});
const page=await browser.newPage({viewport:{width:1400,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/kseniya.html');await page.waitForFunction(()=>window.kseniyaDebug?.getState().ready);await page.waitForTimeout(700);
assert.equal(await page.locator('a[href*="LIZA"],a[href*="index.html"],a[href*="model.html"]').count(),0);
fs.mkdirSync('test-results/kseniya',{recursive:true});await page.screenshot({path:'test-results/kseniya/desktop.png',fullPage:true});
await page.locator('#view2d').click();assert.equal(await page.locator('#plan svg').isVisible(),true);await page.locator('[data-layout="original"]').click();assert.equal(await page.locator('#plan').textContent().then(t=>t.includes('Зал')),true);
await page.locator('[data-layout="new"]').click();assert.equal(await page.locator('#plan').textContent().then(t=>t.includes('Гостиная')),true);
await page.locator('#furniture').uncheck();assert.equal((await page.evaluate(()=>kseniyaDebug.getState())).showFurniture,false);await page.locator('#furniture').check();
const downloadPromise=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'kseniya-plan.svg');
await page.screenshot({path:'test-results/kseniya/plan.png',fullPage:true});
await page.locator('#view3d').click();await page.locator('#cutaway').uncheck();await page.locator('#rotate').click();await page.locator('#zoom-in').click();await page.locator('[data-room="bed1"]').click();assert.match(await page.locator('#room-detail').textContent(),/160/);await page.locator('#reset').click();await page.locator('#cutaway').check();
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-results/kseniya/mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: WebGL, isolated navigation, layouts, 2D/3D, furniture, cutaway, camera, room focus, SVG download, mobile overflow; no page errors.');await browser.close();
