import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-webgl','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1600,height:1080},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>window.apartment?.ready);await page.waitForTimeout(400);
const out={errors,ui:[],walkthrough:[],views:[]};async function shot(name,full=false){await page.waitForTimeout(160);await page.evaluate(()=>{document.querySelector('#toast').style.display='none';window.apartment.render();});await (full?page:page.locator('#viewport')).screenshot({path:path.join(root,'views',name+'.png')});out.views.push(name+'.png');}
await shot('viewer-desktop',true);
for(const id of['A','B','C']){await page.locator('[data-variant="'+id+'"]').click();await page.locator('[data-mode="plan"]').click();await shot(id+'-orthographic');await page.locator('[data-mode="top"]').click();await page.evaluate(()=>window.apartment.setLayer('dimensions',false));await shot(id+'-top');await page.locator('[data-mode="iso"]').click();await shot(id+'-isometric');for(const [i,pos]of [[1,[-7,9,13]],[2,[12,8,-6]]]){await page.evaluate(pos=>{window.apartment.setMode('perspective');window.apartment.cameras.view(pos,[3.2,.3,4.15]);},pos);await shot(id+'-perspective-'+i);}out.ui.push('variant '+id+' camera views rendered');
 const results=await page.evaluate(()=>{const a=window.apartment;const all=[];for(const eye of[1700,1200]){for(const [start,end]of a.layout.routePairs){const r=a.startRoute(start,end);if(!r?.ok){all.push({eye,start,end,ok:false,reason:'no path'});continue;}a.cameras.setEye(eye);let steps=0;while(a.cameras.route?.length&&steps<8000){a.cameras.tick(.05);steps++;}const p=a.camera.position;const target=r.path.at(-1),distance=Math.hypot(p.x*1000-target[0],p.z*1000-target[1]);all.push({eye,start,end,ok:distance<70&&steps<8000,steps,distanceMm:distance,heightMm:p.y*1000});}}return all;});out.walkthrough.push({variant:id,results});assert.ok(results.every(r=>r.ok),'Walkthrough failed '+id+JSON.stringify(results.filter(r=>!r.ok)));}
await page.locator('[data-variant="A"]').click();await page.locator('[data-mode="iso"]').click();await page.evaluate(()=>{const a=window.apartment;a.setLayer('cut',true);a.setLayer('labels',false);});for(const room of['adult','alice','kitchen','living','bath']){await page.locator('[data-room="'+room+'"]').click();await shot('A-room-'+room);}for(const [i,pos]of [[3,[-7,9,-7]],[4,[11,8,14]]]){await page.evaluate(pos=>{window.apartment.setMode('perspective');window.apartment.cameras.view(pos,[3.2,.4,4.15]);},pos);await shot('A-perspective-'+i);}
await page.locator('[data-mode="walk"]').click();await page.locator('[data-room="alice"]').click();await page.locator('[data-eye="1700"]').click();await shot('A-alice-adult-eye');await page.locator('[data-eye="1200"]').click();await shot('A-alice-child-eye');
// Keyboard drives actual camera; forward movement is validated against current furniture.
await page.locator('[data-room="all"]').click();await page.locator('canvas').click({position:{x:750,y:550}});const before=await page.evaluate(()=>window.apartment.camera.position.toArray());await page.keyboard.down('KeyW');await page.waitForTimeout(400);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>window.apartment.camera.position.toArray());assert.ok(Math.hypot(after[0]-before[0],after[2]-before[2])>.05);out.ui.push('WASD moves camera');const yawBefore=await page.evaluate(()=>window.apartment.cameras.yaw);await page.mouse.move(900,600);await page.mouse.down();await page.mouse.move(1060,640,{steps:8});await page.mouse.up();assert.ok(Math.abs((await page.evaluate(()=>window.apartment.cameras.yaw))-yawBefore)>.1);out.ui.push('drag mouse look changes yaw and pitch');await page.locator('canvas').dblclick({position:{x:750,y:550}});await page.waitForTimeout(200);out.pointerLock=await page.evaluate(()=>!!document.pointerLockElement);await page.keyboard.press('Escape');
await page.locator('[data-mode="iso"]').click();await page.locator('#furniture').uncheck();assert.equal(await page.evaluate(()=>window.apartment.state.furniture),false);await page.locator('#furniture').check();await page.locator('#walls').uncheck();await page.locator('#walls').check();await page.locator('#dimensions').check();await page.locator('#zones').check();await shot('A-operating-zones');await page.locator('#zones').uncheck();await page.locator('#dimensions').uncheck();await page.locator('#cut').check();await page.locator('#labels').check();
await page.evaluate(()=>window.apartment.selectObject('dishwasher'));await page.locator('#open-appliance').click();assert.equal(await page.evaluate(()=>window.apartment.state.applianceOpen),'dishwasher');await shot('A-open-dishwasher');await page.locator('#open-appliance').click();await page.evaluate(()=>window.apartment.selectObject(null));out.ui.push('appliance opening toggle with collision leaf');await page.locator('#compare').click();assert.ok(await page.locator('dialog').isVisible());assert.equal(await page.locator('[data-route]').count(),11);await page.locator('[data-route="entry,alice"]').click();assert.equal(await page.locator('dialog').isVisible(),false);out.ui.push('comparison modal and route button');await page.locator('[data-mode="iso"]').click();await page.locator('#cut').check();
for(const id of['A','B','C']){await page.locator('[data-variant="'+id+'"]').click();const data=await page.evaluate(async()=>Array.from(new Uint8Array(await window.apartment.exportModel())));fs.writeFileSync(path.join(root,'MASTER-'+id+'.glb'),Buffer.from(data));assert.equal(Buffer.from(data).subarray(0,4).toString(),'glTF');}
await page.locator('[data-variant="A"]').click();await page.locator('[data-mode="iso"]').click();await page.locator('#cut').check();await shot('viewer-desktop',true);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await page.screenshot({path:path.join(root,'views','viewer-mobile.png'),fullPage:true});out.views.push('viewer-mobile.png');out.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(out.mobileOverflow,false);
// Reopen bundled standalone file offline: no network dependency for model or controls.
await page.setOfflineMode?.(true).catch?.(()=>{});
await page.context().setOffline(true);await page.goto('file://'+path.join(root,'index.html'));await page.waitForFunction(()=>window.apartment?.ready);out.offline=true;await browser.close();assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(root,'browser-qa-results.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({views:out.views.length,walkthroughs:out.walkthrough.reduce((n,v)=>n+v.results.length,0),ui:out.ui,errors,offline:true,pointerLock:out.pointerLock,mobileOverflow:out.mobileOverflow},null,2));
