import fs from 'node:fs';
const manifest=JSON.parse(fs.readFileSync('docs/engineering/manifest.json','utf8'));
fs.writeFileSync('index.html',fs.readFileSync('client.template.html','utf8').replace('/*CLIENT_STYLE*/',fs.readFileSync('src/project/client.css','utf8')));
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${e(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const sheets=manifest.sheets.map(s=>`<button data-sheet="${s.id}" aria-pressed="false"><b>${s.id}</b><span>${e(s.title)}</span></button>`).join('');
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Лиза / D·01 — чертежи и ведомости</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f2eb;color:#252922;font:16px/1.6 Arial,sans-serif}a{color:inherit;text-underline-offset:4px}header{padding:22px 5vw;border-bottom:1px solid #c9ccbf;display:flex;justify-content:space-between;gap:20px;font-size:14px}main{max-width:1450px;margin:auto;padding:55px 5vw}h1{font:400 clamp(38px,5vw,68px)/1.1 Georgia,serif;margin:15px 0 25px}h2{font:400 33px Georgia,serif;margin:60px 0 22px}p{max-width:940px;color:#60665c}.eyebrow{font-size:12px;letter-spacing:.16em}.notice{padding:20px 25px;border-left:3px solid #9a6d47;background:#eae7df;margin:30px 0}.notice p{margin:7px 0 0;font-size:14px}.facts{display:flex;gap:45px;flex-wrap:wrap;margin:40px 0}.facts b{font:30px Georgia,serif;display:block}.facts span{font-size:12px;color:#666}.viewer{display:grid;grid-template-columns:260px 1fr;gap:24px;align-items:start}.sheet-list{max-height:670px;overflow:auto;border-top:1px solid #c9ccbf}.sheet-list button{width:100%;display:flex;text-align:left;gap:14px;border:0;border-bottom:1px solid #d6d7cd;background:none;padding:16px 10px;cursor:pointer;font:13px/1.4 Arial,sans-serif}.sheet-list button[aria-pressed=true]{background:#293026;color:white}.sheet-list b{min-width:32px}.drawing img{width:100%;height:auto;display:block;background:#faf9f5;border:1px solid #c9ccbf}.drawing p{display:flex;justify-content:space-between;font-size:13px;gap:20px}.downloads{display:flex;gap:15px;flex-wrap:wrap;margin:22px 0}.downloads a{padding:12px 18px;background:#293026;color:white;text-decoration:none;font-size:14px}.table-wrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid #d2d4c9;padding:12px 14px;vertical-align:top}th{background:#e6e6dc;white-space:nowrap}td{min-width:60px}td:nth-child(2){min-width:200px}details{border-bottom:1px solid #c9ccbf;padding:20px 0}summary{cursor:pointer;font-size:18px}summary+div{margin:20px 0}.sources{font-size:14px}.sources li{margin:15px 0}.sources small{display:block;color:#666}button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid #ad8052;outline-offset:3px}footer{border-top:1px solid #c9ccbf;padding:30px 5vw;font-size:12px;color:#666}@media(max-width:800px){main{padding:30px 5vw}.viewer{grid-template-columns:1fr}.sheet-list{display:flex;max-height:none;overflow:auto}.sheet-list button{min-width:200px}.drawing p{flex-wrap:wrap}.facts{gap:25px}.facts b{font-size:25px}table{font-size:12px}header{font-size:12px}h2{font-size:29px}}@media print{header,.sheet-list,.downloads{display:none}main{padding:0}.viewer{display:block}.notice{font-size:12px}}
</style></head><body><header><a href="index.html">Лиза / Тихая геология</a><a href="output/pdf/Liza-D01-client-album.pdf">Скачать альбом PDF</a></header><main><div class="eyebrow">D / 01 · Редакция 01 · 29.09.2026</div><h1>Чертежи.<br>Связи. Ведомости.</h1><p>Утверждённая интерьерная концепция переведена в систему планов и проектных точек. Комплект предназначен для обсуждения с заказчиком, замерщиком, мебельщиками и инженерами.</p><aside class="notice"><strong>Предварительный комплект. Не для монтажа.</strong><p>Не получены обмер, стояки, вентшахты и параметры электроввода. Кабели, защита, диаметры, уклоны и инженерные трассы не назначены без расчёта. Розетки и свет здесь — авторское задание инженеру, а не подписанный проект ЭОМ.</p></aside><div class="facts"><div><b>22 листа</b><span>связанный комплект схем</span></div><div><b>14 групп</b><span>предварительная структура электрики</span></div><div><b>25,21 кВт</b><span>сумма гипотетических нагрузок</span></div><div><b>6 приборов</b><span>точки водоснабжения / канализации</span></div></div><section class="viewer" aria-label="Просмотр чертежей"><nav class="sheet-list" aria-label="Листы альбома">${sheets}</nav><div class="drawing"><img id="sheet-image" src="docs/engineering/A01.svg" alt="План мебели и оборудования" width="1190" height="842"><p><span id="sheet-caption">A01 / План мебели и оборудования</span><a id="sheet-link" href="docs/engineering/A01.svg" target="_blank" rel="noopener">Открыть лист отдельно</a></p></div></section><div class="downloads"><a href="output/pdf/Liza-D01-client-album.pdf">PDF / 27 страниц</a><a href="docs/engineering/outlets.csv" download>Розетки / CSV</a><a href="docs/engineering/circuits.csv" download>Группы / CSV</a><a href="docs/engineering/plumbing.csv" download>Сантехника / CSV</a></div>
<h2>Электрика: что посчитано</h2><p>34 силовых механизма и 4 разъёма данных в 25 постах. 16 световых позиций с суммарной условной мощностью 260 Вт. Все X / Y — от внутреннего верхнего левого угла модели; H — от чистого пола.</p>
${table(['Группа','Назначение','P, Вт*','I при 230 В, А*','Точки'],manifest.circuits.map(c=>[c.id,c.name,c.w,c.currentEstimate,c.points.join(', ')]))}
<p><small>* Нагрузки предположены до выбора техники; токи оценены при cosφ=1 и не используются для выбора кабелей / автоматов. Электрическая варочная — допущение. Кондиционер, бойлер, тёплый пол и сушильная машина не включены.</small></p>
<h2>Одновременная работа</h2>${table(['Сценарий, не нормативный коэффициент спроса','P, кВт','I при 230 В, А'],manifest.power.scenarios.map(s=>[s.name,(s.w/1000).toFixed(3),s.currentAt230]))}<p>Это прозрачные сценарии использования. Они не заменяют расчёт спроса, технические условия и подбор вводного аппарата.</p>
<details><summary>Ведомость розеток и данных / 25 постов</summary>${table(['ID','Назначение','X','Y','H','Кол.','Группа'],manifest.points.map(p=>[p.id,p.name,p.x,p.y,p.h,p.count,p.group]))}</details>
<details><summary>Свет и управление / 16 позиций</summary>${table(['ID','Назначение','X / Y','H','Вт*','Управление'],manifest.lights.map(p=>[p.id,p.name,p.x+' / '+p.y,p.h,p.w,p.control]))}${table(['ID','Функция','X / Y','H'],manifest.switches.map(p=>[p.id,p.name,p.x+' / '+p.y,p.h]))}</details>
<details><summary>Сантехнические подключения / 6 приборов</summary>${table(['ID','Прибор','X / Y','Системы','Отметки'],manifest.plumbing.map(p=>[p.id,p.equipment,p.x+' / '+p.y,p.connections,p.height]))}<p>Схема ВК показывает функциональные подключения. Стояк, коллектор и отметки выпуска неизвестны, поэтому реальные трассы, метраж, диаметры и уклоны не выдуманы.</p></details>
<h2>Перед выпуском в монтаж</h2><ol><li>Контрольный обмер, высоты и конструктив; план БТИ / застройщика и мокрые зоны.</li><li>Фото и положение стояков, канализационных выпусков и вентшахт.</li><li>Выделенная мощность, фазы, система заземления и схема существующего щита.</li><li>Паспорта бытовой техники, сантехники, светильников и дверных систем.</li><li>Расчёты ЭОМ и ВК; согласование вентиляции, узлов и монтажных трасс.</li></ol>
<h2>Российская практика и источники</h2><p>Комплект организован по логике российской интерьерной документации: планы, отдельные схемы света и управления, высоты точек, развёртки, ведомости и статус каждого выпуска. Условные знаки в схемах авторские, расшифрованы в листах; полное соответствие рабочей документации ГОСТ не заявляется.</p><ul class="sources">${manifest.sources.map(s=>`<li><a href="${e(s.url)}" target="_blank" rel="noopener">${e(s.title)}</a><small>${e(s.note)}</small></li>`).join('')}</ul></main><footer>Концепция D / 01 утверждена заказчиком. Инженерный раздел предварительный. Размеры по условной модели, не по обмеру.</footer><script>const sheets=${JSON.stringify(manifest.sheets).replace(/</g,'\\u003c')};function select(id){const s=sheets.find(s=>s.id===id);if(!s)return;document.querySelector('#sheet-image').src=s.path;document.querySelector('#sheet-image').alt=s.title;document.querySelector('#sheet-caption').textContent=s.id+' / '+s.title;document.querySelector('#sheet-link').href=s.path;document.querySelectorAll('[data-sheet]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.sheet===id)));history.replaceState(null,'','#'+id);}document.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>select(b.dataset.sheet));select(sheets.some(s=>s.id===location.hash.slice(1))?location.hash.slice(1):'A01');</script></body></html>`;
fs.writeFileSync('engineering.html',html);
console.log('Built approved client case and engineering viewer');
