import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';import {colliders,findRoute,canStand,moveWithCollision} from '../src/interaction/collision.js';
const dir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const geometry=JSON.parse(fs.readFileSync(path.join(dir,'src/data/geometry.json')));const baseLayouts=JSON.parse(fs.readFileSync(path.join(dir,'src/data/layouts.json'))),referenceLayout=JSON.parse(fs.readFileSync(path.join(dir,'src/data/layout-reference.json'))),layouts=[referenceLayout,...baseLayouts];
function overlap(a,b){return Math.min(a.x+a.width,b.x+b.width)-Math.max(a.x,b.x)>.5&&Math.min(a.y+a.depth,b.y+b.depth)-Math.max(a.y,b.y)>.5&&Math.min((a.elevation||0)+a.height,(b.elevation||0)+b.height)-Math.max(a.elevation||0,b.elevation||0)>.5;}
const result={avatarDiameterMm:500,gridMm:75,routeScope:'closed appliances, open room doors, rigid envelope furniture; not comfort certification',variants:[],tests:[]};let failures=[];
for(const l of layouts){const obstacles=colliders(geometry,l),routes=l.routePairs.map(([a,b])=>({from:a,to:b,...findRoute(l.routes[a],l.routes[b],geometry,obstacles,{radius:250})}));let collisions=[];for(let i=0;i<l.furniture.length;i++){const a=l.furniture[i];for(let j=i+1;j<l.furniture.length;j++)if(overlap(a,l.furniture[j]))collisions.push([a.id,l.furniture[j].id]);for(const b of [...geometry.walls,...l.partitions])if(overlap(a,b))collisions.push([a.id,b.id]);}for(const r of routes)if(!r.ok)failures.push(l.id+': '+r.from+'→'+r.to+' '+r.reason);if(collisions.length)failures.push(l.id+' collisions '+JSON.stringify(collisions));result.variants.push({id:l.id,collisions,routes:routes.map(r=>({...r,path:r.path}))});
 const r=routes.find(r=>r.ok);if(r){for(let i=1;i<r.path.length;i++){const prev=r.path[i-1],p=r.path[i];const moved=moveWithCollision({x:prev[0],y:prev[1]},p[0]-prev[0],p[1]-prev[1],geometry,obstacles,250);if(Math.hypot(moved.x-p[0],moved.y-p[1])>1)failures.push(l.id+' route movement collision at '+i);}}
 assert.equal(canStand(50,3500,geometry,obstacles,250),false);assert.equal(canStand(1400,6500,geometry,obstacles,250),false);assert.equal(canStand(-500,2000,geometry,obstacles,250),false);
 const wallTest=moveWithCollision({x:6000,y:4000},5000,0,geometry,obstacles,250);assert.ok(wallTest.x<=6150.1);result.tests.push(l.id+': outside, wall and bed blocked; swept movement does not tunnel');
 const bed=l.furniture.find(o=>o.id==='adult-bed');assert.deepEqual(bed.mattress,[1600,2000]);assert.equal(l.furniture.find(o=>o.id==='alice-desk').width,1200);
}
result.failures=failures;fs.writeFileSync(path.join(dir,'qa-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({variants:result.variants.map(v=>({id:v.id,collisions:v.collisions,routes:v.routes.map(r=>({route:r.from+' → '+r.to,ok:r.ok,snap:r.endpointSnapMm,reason:r.reason}))})),failures},null,2));if(failures.length)process.exitCode=1;
