import * as THREE from 'three';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {geometry,layouts,project,mm,polygonArea,roomNames} from './data/model.js';
import {materials} from './scene/materials.js';
import {addLighting} from './scene/lighting.js';
import {createArchitecture,createFurniture,box,dimensionLine} from './scene/build.js';
import {Cameras} from './interaction/cameras.js';
import {colliders,canStand,findRoute} from './interaction/collision.js';
import {openingLeaf} from './interaction/appliances.js';
const $=s=>document.querySelector(s);
const state={variant:'A',furniture:true,walls:true,cut:true,labels:true,dimensions:false,zones:false,doors:true,mode:'iso',selected:null,applianceOpen:null};
let layout=layouts[0],root,annotations=[],obstacles=[];const scene=new THREE.Scene();scene.background=new THREE.Color(0xe9ede7);const mats=materials();addLighting(scene);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch(e){$('#canvas-container').innerHTML='<p style="padding:100px 30px">WebGL недоступен. Откройте модель в Chrome или Safari с аппаратным ускорением. Планы доступны в папке views.</p>';throw e;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;$('#canvas-container').append(renderer.domElement);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0xe9ede7,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.115;ground.receiveShadow=true;scene.add(ground);
const cameras=new Cameras(renderer.domElement,geometry,()=>obstacles);
const annotationLayer=$('#annotation-layer');let highlight=null;
function dispose(group){group?.traverse(o=>{o.geometry?.dispose();});}
function addAnnotation(text,x,y,dim=false,z=30){const el=document.createElement('div');el.className='annotation'+(dim?' dim':'');el.textContent=text;annotationLayer.append(el);annotations.push({el,p:new THREE.Vector3(mm(x),mm(z),mm(y))});}
function serviceZone(o){const f=o.front||'south';let reach=['fridge','dishwasher','washer','hob'].includes(o.type)?650:['chair','stool'].includes(o.type)?300:600;
 if(o.type==='bed'||['upper','tv','mirror','shower','shelf'].includes(o.type))return null;
 if(['chair','stool'].includes(o.type))return{x:o.x-50,y:o.y-50,width:o.width+100,depth:o.depth+100,label:'Стул + резерв движения'};
 const zone={id:o.id+'-use',x:o.x,y:o.y,width:o.width,depth:o.depth,label:o.opening==='sliding'?'Доступ к купе':'Открывание / использование'};
 if(f==='south'){zone.y+=o.depth;zone.depth=reach;}if(f==='north'){zone.y-=reach;zone.depth=reach;}if(f==='east'){zone.x+=o.width;zone.width=reach;}if(f==='west'){zone.x-=reach;zone.width=reach;}return zone;}
function rebuild(){if(root){scene.remove(root);dispose(root);}root=new THREE.Group();root.name='MASTER_APARTMENT_'+layout.id;scene.add(root);const plan=state.mode==='plan';renderer.shadowMap.enabled=!plan;scene.traverse(o=>{if(o.isLight&&o.shadow)o.castShadow=!plan;});for(const mat of Object.values(mats))mat.needsUpdate=true;root.add(createArchitecture(geometry,layout,mats,{cut:state.cut,plan,walls:state.walls,doorsOpen:state.doors}));
 const furniture=new THREE.Group();furniture.name='FURNITURE_'+layout.id;furniture.visible=state.furniture;root.add(furniture);for(const o of layout.furniture){if(plan&&(o.elevation||0)>1200)continue;const obj=createFurniture(o,mats);furniture.add(obj);}
 const decor=new THREE.Group();decor.name='DECOR_FUTURE';root.add(decor);
 const anno=new THREE.Group();anno.name='ANNOTATIONS';root.add(anno);annotations=[];annotationLayer.replaceChildren();
 if(state.labels&&state.mode!=='walk'){for(const r of layout.rooms){const p=state.dimensions?({adult:[1550,6650],alice:[4750,5900],kitchen:[4950,1250]}[r.id]||[r.x,r.y]):[r.x,r.y];addAnnotation(r.name+(r.area?' · '+r.area.toFixed(1)+' м²':''),p[0],p[1],false,50);}}
 if(state.dimensions&&state.mode!=='walk'){dimensionLine(anno,[0,-420],[6400,-420]);addAnnotation('6400',3200,-450,true);dimensionLine(anno,[-430,0],[-430,8300]);addAnnotation('8300*',-430,4050,true);dimensionLine(anno,[6820,0],[6820,7440]);addAnnotation('7440*',6820,3700,true);for(const c of layout.clearances){const from=[c.x-(c.axis==='x'?c.length/2:0),c.y-(c.axis==='y'?c.length/2:0)],to=[c.x+(c.axis==='x'?c.length/2:0),c.y+(c.axis==='y'?c.length/2:0)];dimensionLine(anno,from,to);addAnnotation(c.value+' мм',c.x,c.y,true,55);}}
 if(state.zones){for(const o of layout.furniture){const z=serviceZone(o);if(!z)continue;const mat=new THREE.MeshBasicMaterial({color:0x8ea990,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide});box(anno,mat,z.x,z.y,z.width,z.depth,8,20);const pts=[[z.x,z.y],[z.x+z.width,z.y],[z.x+z.width,z.y+z.depth],[z.x,z.y+z.depth],[z.x,z.y]];for(let i=1;i<pts.length;i++)dimensionLine(anno,pts[i-1],pts[i],0x789479);}
 for(const d of layout.doors){if(d.mechanism?.includes('sliding'))continue;let hinge,theta0,theta1;if(d.axis==='x'){hinge=[d.x,d.swing==='outward'?d.y:d.y+120];theta0=0;theta1=d.swing==='outward'?-Math.PI/2:Math.PI/2;}else{hinge=[d.x+120,d.y+d.width];theta0=-Math.PI/2;theta1=0;}const p=[];for(let i=0;i<=24;i++){const t=theta0+(theta1-theta0)*i/24;p.push([hinge[0]+Math.cos(t)*d.width,hinge[1]+Math.sin(t)*d.width]);}for(let i=1;i<p.length;i++)dimensionLine(anno,p[i-1],p[i],0xad9d74);}}
 obstacles=colliders(geometry,layout,{furniture:state.furniture,doorsOpen:state.doors});if(state.applianceOpen&&state.furniture){const item=layout.furniture.find(o=>o.id===state.applianceOpen);const leaf=item&&openingLeaf(item);if(leaf){box(root,mats.joinery,leaf.x,leaf.y,leaf.width,leaf.depth,leaf.height,leaf.elevation,leaf.id);obstacles.push(leaf);}}selectObject(state.selected);updateUI();}
function selectObject(id){if(highlight){scene.remove(highlight);highlight.geometry?.dispose();highlight=null;}state.selected=id;const o=layout.furniture.find(o=>o.id===id);if(!o){$('#selection').innerHTML='<span class="eyebrow">ОБЪЕКТЫ В МАСШТАБЕ</span><p>Нажмите на мебель,<br>чтобы увидеть её размеры.</p>';return;}
 const bounds=new THREE.Box3(new THREE.Vector3(mm(o.x),mm(o.elevation||0),mm(o.y)),new THREE.Vector3(mm(o.x+o.width),mm((o.elevation||0)+o.height),mm(o.y+o.depth)));highlight=new THREE.Box3Helper(bounds,0x608769);scene.add(highlight);
 $('#selection').innerHTML='<span class="eyebrow">'+roomNames[o.room]+'</span><strong>'+o.label+'</strong><div class="dimensions">'+o.width+' × '+o.depth+' × '+o.height+'</div><p>Габарит Ш × Г × В, мм<br>x '+o.x+' · y '+o.y+(o.mattress?'<br>Матрас '+o.mattress.join(' × '):'')+'</p>'+(openingLeaf(o)?'<button id="open-appliance">'+(state.applianceOpen===id?'Закрыть дверцу':'Проверить открытую дверцу')+'</button>':'');if($('#open-appliance'))$('#open-appliance').onclick=()=>{state.applianceOpen=state.applianceOpen===id?null:id;rebuild();toast('Показан условный габарит дверцы. Точную фурнитуру уточним по технике.');};}
function setMode(mode){state.mode=mode;if(mode==='walk'){state.cut=false;state.walls=true;state.doors=true;$('#cut').checked=false;$('#walls').checked=true;$('#doors').checked=true;}else if(state.mode==='plan')state.dimensions=true;cameras.setMode(mode);rebuild();}
function setVariant(id){layout=layouts.find(v=>v.id===id)||layouts[0];state.variant=layout.id;state.selected=null;state.applianceOpen=null;cameras.setMode(state.mode);rebuild();}
function updateUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));document.querySelectorAll('.variant').forEach(b=>b.classList.toggle('active',b.dataset.variant===layout.id));$('#variant-caption').textContent=layout.id+' / '+layout.name.toUpperCase();$('#view-caption').textContent=({iso:'Изометрия',orbit:'Свободное вращение',plan:'Ортографический план',top:'Вид сверху · перспектива',perspective:'Перспектива',walk:'Прогулка · '+cameras.eye+' мм'})[state.mode]+(state.mode!=='walk'&&state.cut?' · срез стен':'');$('#walk-panel').hidden=state.mode!=='walk';$('#canvas-help').hidden=state.mode==='walk';$('#layout-summary').textContent=layout.id==='A'?'Рекомендуемый вариант · около 50 м²* · геометрия требует обмера':layout.subtitle+' · около 50 м²*';for(const k of['furniture','walls','cut','labels','dimensions','zones','doors'])$('#'+k).checked=state[k];}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4000);}
$('#variants').innerHTML=layouts.map(v=>'<button class="variant '+(v.id==='A'?'active':'')+'" data-variant="'+v.id+'"><span class="variant-letter">'+v.id+'</span><span><strong>'+v.name+(v.recommended?'<span class="tag">ВЫБОР</span>':'')+'</strong><small>'+v.subtitle+'</small></span></button>').join('');
$('#variants').onclick=e=>{const b=e.target.closest('[data-variant]');if(b)setVariant(b.dataset.variant);};$('#modes').onclick=e=>{const b=e.target.closest('[data-mode]');if(b)setMode(b.dataset.mode);};$('#reset').onclick=()=>{cameras.setMode(state.mode);selectObject(null);};for(const k of['furniture','walls','cut','labels','dimensions','zones','doors'])$('#'+k).onchange=e=>{state[k]=e.target.checked;rebuild();if(state.mode==='walk'&&!canStand(cameras.camera.position.x*1000,cameras.camera.position.z*1000,geometry,obstacles,250)){cameras.teleport(layout.routes.entry);toast('Положение камеры сброшено ко входу, чтобы избежать пересечения.');}};
const raycaster=new THREE.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||state.mode==='walk')return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),cameras.camera);const hit=raycaster.intersectObjects(root.children,true).find(h=>h.object.userData.id&&layout.furniture.some(o=>o.id===h.object.userData.id));selectObject(hit?.object.userData.id||null);});
const roomViews={adult:{pos:[5.5,6,10.1],target:[1.55,.4,6.25],walk:[2808,6350],look:[1500,6500]},alice:{pos:[8,6,9],target:[4.8,.3,5.95],walk:[4950,5700],look:[4200,6900]},kitchen:{pos:[9,6,6.4],target:[4.3,.6,1.3],walk:[4250,1100],look:[4350,100]},living:{pos:[5.5,4.8,6.9],target:[1.3,.3,3.2],walk:[2750,3000],look:[1000,3600]},bath:{pos:[5,5,5.5],target:[1.1,.4,1.2],walk:[1150,1150],look:[400,400]}};
function viewRoom(name){if(name==='all'){cameras.setMode(state.mode);return;}const v=roomViews[name];if(state.mode==='walk'){if(!cameras.teleport(v.walk,v.look))toast('Эта точка занята в варианте '+layout.id+'. Начните прогулку от входа.');}else{state.mode='perspective';state.cut=true;cameras.view(v.pos,v.target);rebuild();}}
$('#rooms').onclick=e=>{const b=e.target.closest('[data-room]');if(b)viewRoom(b.dataset.room);};document.querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{cameras.setEye(Number(b.dataset.eye));document.querySelectorAll('[data-eye]').forEach(c=>c.classList.toggle('active',c===b));updateUI();});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{cameras.keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>cameras.keys.delete(b.dataset.key);});
const routeNames={entry:'Вход',storage:'Хранение',kitchen:'Кухня',bar:'Стойка',adult:'Ваша спальня',alice:'Алиса',adultBed:'Кровать',adultWardrobe:'Шкаф',aliceBed:'Кровать Алисы',aliceDesk:'Стол Алисы',bathroom:'Санузел',fridge:'Холодильник',dishwasher:'ПММ',sofa:'Диван'};
function routeResult(a,b){return findRoute(layout.routes[a],layout.routes[b],geometry,colliders(geometry,layout),{radius:250});}
function startRoute(a,b){const res=routeResult(a,b);if(!res.ok){toast('Маршрут не найден: '+res.reason);return res;}state.applianceOpen=null;setMode('walk');cameras.teleport(res.path[0]);cameras.route=res.path.slice(1);$('#details').close();toast(routeNames[a]+' → '+routeNames[b]+' · '+(res.lengthMm/1000).toFixed(1)+' м');return res;}
function modal(html){$('#dialog-content').innerHTML=html;$('#details').showModal();}
$('#close-dialog').onclick=()=>$('#details').close();$('#details').addEventListener('click',e=>{if(e.target===$('#details'))$('#details').close();});
function showAssumptions(){modal('<h2>Размеры с оговорками.</h2><p>Главная ширина <b>6400 мм</b> взята из цепочки 3175 + 250 + 2975. Вертикали и окна на исходном изображении противоречивы: модель — проверяемая гипотеза, а не подтверждённый обмер. *Площадь контура '+(polygonArea(geometry.floor)/1e6).toFixed(2)+' м² — результат этой гипотезы, в описании округлена до «около 50 м²».</p>'+geometry.assumptions.map(a=>'<div class="assumption"><b>'+a.id+'</b><p>'+a.text+'</p></div>').join('')+'<p class="small">Вход сверху справа. Окна снизу. Север по плану неизвестен. Схема новых перегородок не означает согласование перепланировки.</p><div class="export-row"><button id="data-download">Скачать данные модели JSON</button><a href="geometry-notes.md" target="_blank">Разбор обмерного плана ↗</a></div>');$('#data-download').onclick=()=>downloadJSON();}
$('#assumptions').onclick=showAssumptions;
$('#report').onclick=()=>{modal('<h2>Основа, которую можно развивать.</h2><p>Этап 1: геометрия, три планировки, мебель в реальных габаритах и прогулка с коллизиями. Вариант A рекомендован для вашего выбора; он ещё не помечен как утверждённый.</p><p>Данные хранятся в миллиметрах. В сцене 1 единица = 1 метр. Стены, мебель, материалы, свет, будущий декор и камеры разделены.</p><h3>Как пользоваться</h3><p>Переключайте варианты слева. «План» — ортографический вид без перспективных искажений. «Вращение» и «Изометрия» позволяют поворачивать модель, колесо меняет масштаб, правая кнопка сдвигает вид. «Прогулка»: WASD / стрелки, тяните мышью для обзора или дважды нажмите на сцену. Высота взрослого1700, Алисы1200 мм. Кнопки комнат переносят к проверенным точкам.</p><p>Радиус коллизии250 мм — условное тело диаметром500 мм. Это проверка геометрической достижимости, а не универсальная оценка комфорта. Рабочие зоны мебели показаны отдельно; доступ к отдельным приборам используется по очереди.</p><h3>Сохранить и продолжить</h3><p>PNG сохраняет текущий ракурс. GLB экспортирует полноценную геометрию выбранного варианта, независимо от экранного среза. JSON сохраняет все три варианта и исходные допущения.</p><div class="export-row"><button id="data-download">↓ Данные JSON</button><a href="REPORT.html" target="_blank">Полный отчёт и альбом видов ↗</a></div><p class="small">Камера вращения: <a href="https://threejs.org/docs/pages/OrbitControls.html" target="_blank">Three.js OrbitControls</a>. Экспорт: <a href="https://threejs.org/docs/pages/GLTFExporter.html" target="_blank">GLTFExporter</a>.</p>');$('#data-download').onclick=()=>downloadJSON();};
$('#compare').onclick=()=>{const rows=[['Ежедневная жизнь','Гибкая общая зона','Нужно обходить шкаф','Больше обходов дивана'],['Приватность','Две комнаты; купе детской','Как A','Как A'],['Хранение','Базовое, шкафы1100/1600/1500','Больше кухонных модулей','Больше санузел'],['Кухня','Прямая3300, проход1500','Расширенная; вход1150','Прямая3300, без духовки'],['Детская / рабочие места','Стол1200; спальня с рабочим1000','То же','То же'],['Проходы','735 у кровати;625 у стола','930 за барными стульями','700 перед спальнями'],['Пространство / окна','Окна в спальнях; общий свет условный','Шкаф дробит общую зону','Открытее центр, ТВ на пути'],['Сложность / будущий дизайн','Умеренная; гибкая стойка','Выше; больше столярных изделий','Больше мокрая зона'],['Спорные перестроения','Мокрые зоны неизвестны','То же + длиннее кухня','То же + расширение санузла']];modal('<h2>Три варианта. Один приоритет.</h2><p>Рекомендую <b>A «Баланс»</b>: самая понятная связь прихожей, кухни и двух спален. Сравнение качественное, без искусственных баллов. Во всех вариантах размеры помещений и инженерия требуют уточнения.</p><div class="table-wrap"><table><tr><th>Критерий</th><th>A · Баланс</th><th>B · Кухня+</th><th>C · Семейный</th></tr>'+rows.map(r=>'<tr>'+r.map(t=>'<td>'+t+'</td>').join('')+'</tr>').join('')+'</table></div><h3>'+layout.id+' · '+layout.name+': проверенные маршруты</h3><p class="small">Проверка сеткой75 мм, телоØ500 мм, мебель и открытые двери включены. Нажмите маршрут для автоматической прогулки; WASD прерывает её. Перемещение по маршруту использует те же коллизии.</p><div class="route-grid">'+layout.routePairs.map(([a,b])=>{const r=routeResult(a,b);return'<button data-route="'+a+','+b+'">'+(r.ok?'✓ ':'! ')+routeNames[a]+' → '+routeNames[b]+(r.ok?' · '+(r.lengthMm/1000).toFixed(1)+' м':' · нет прохода')+'</button>';}).join('')+'</div><h3>Честная оценка компактности</h3><p>Проход у окна взрослой спальни550 мм — локальный. В детской справа от стола625 мм. Купейные шкафы не требуют радиуса распахивания; к ним нужен свободный фронт. У ванной и стиралки рабочие зоны частично общие: пользоваться ими одновременно тесно.</p>');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>startRoute(...b.dataset.route.split(',')));};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
function downloadJSON(){download(new Blob([JSON.stringify({project,geometry,layouts,selectedLayout:layout.id},null,2)],{type:'application/json'}),'MASTER-APARTMENT.json');}
function exportModel(){const exportRoot=new THREE.Group();exportRoot.name='MASTER_APARTMENT_'+layout.id;exportRoot.userData={units:'meters',sourceDataUnits:'mm',layout:layout.id,approvalStatus:project.approvalStatus};exportRoot.add(createArchitecture(geometry,layout,mats,{cut:false,plan:false,walls:true,doorsOpen:true}));for(const o of layout.furniture)exportRoot.add(createFurniture(o,mats));return new Promise((resolve,reject)=>new GLTFExporter().parse(exportRoot,resolve,reject,{binary:true,onlyVisible:true}));}
$('#export').onclick=async()=>{try{download(new Blob([await exportModel()],{type:'model/gltf-binary'}),'MASTER-'+layout.id+'.glb');toast('Полная модель '+layout.id+' сохранена.');}catch(e){toast('Ошибка экспорта: '+e.message);}};
$('#snapshot').onclick=()=>{renderer.render(scene,cameras.camera);renderer.domElement.toBlob(blob=>download(blob,'apartment-'+layout.id+'-'+state.mode+'.png'));};
new ResizeObserver(()=>{const {width,height}=$('#canvas-container').getBoundingClientRect();renderer.setSize(width,height);cameras.resize(width,height);}).observe($('#canvas-container'));
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);cameras.tick(clock.getDelta());for(const a of annotations){const p=a.p.clone().project(cameras.camera);a.el.style.left=(p.x*.5+.5)*renderer.domElement.clientWidth+'px';a.el.style.top=(-p.y*.5+.5)*renderer.domElement.clientHeight+'px';a.el.style.display=p.z<1&&p.z>-1?'':'none';}renderer.render(scene,cameras.camera);}rebuild();animate();
window.apartment={state,geometry,layouts,project,get layout(){return layout},get camera(){return cameras.camera},get renderer(){return renderer},cameras,setVariant,setMode,viewRoom,rebuild,selectObject,routeResult,startRoute,canStand:(x,y)=>canStand(x,y,geometry,obstacles,250),setLayer:(key,v)=>{state[key]=v;rebuild();},exportModel,serviceZone,render:()=>renderer.render(scene,cameras.camera),ready:true};
