import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {geometry,layouts,project,mm,polygonArea,roomNames} from './data/model.js';
import {materials,disposeMaterials,prepareTextures} from './scene/materials.js';
import {interiorStyles} from './data/interior-styles.js';
import {addLighting} from './scene/lighting.js';
import {createArchitecture,createFurniture,createDecor,box,dimensionLine} from './scene/build.js';
import {createStudio,roomSpec} from './scene/studio.js';
import {Cameras} from './interaction/cameras.js';
import {colliders,canStand,findRoute} from './interaction/collision.js';
import {openingLeaf} from './interaction/appliances.js';
async function main(){
await prepareTextures();
const $=s=>document.querySelector(s);
const requestedStyle=new URLSearchParams(location.search).get('style');
const requestedVariant=new URLSearchParams(location.search).get('variant');
const initialStyle=interiorStyles.find(s=>s.id===requestedStyle)||interiorStyles[0];
const initialLayout=layouts.find(l=>l.id===requestedVariant)||layouts[0];
const state={variant:initialLayout.id,style:initialStyle.id,furniture:true,walls:true,cut:true,labels:false,focus:null,dimensions:false,zones:false,doors:true,mode:'iso',selected:null,applianceOpen:null};
let needsRender=true;let layout=initialLayout,root,annotations=[],obstacles=[];const scene=new THREE.Scene();scene.background=new THREE.Color(initialStyle.background);let mats=materials(initialStyle);const lighting=addLighting(scene);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch(e){$('#canvas-container').innerHTML='<p style="padding:100px 30px">WebGL недоступен. Откройте модель в Chrome или Safari с аппаратным ускорением. <a href="studio.html">Открыть галерею рендеров ↗</a></p>';throw e;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=initialStyle.exposure;$('#canvas-container').append(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer);const roomEnvironment=new RoomEnvironment();const environment=pmrem.fromScene(roomEnvironment,.04);scene.environment=environment.texture;scene.environmentIntensity=.45;roomEnvironment.dispose();pmrem.dispose();
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:initialStyle.background,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.115;ground.receiveShadow=true;scene.add(ground);
const cameras=new Cameras(renderer.domElement,geometry,()=>obstacles,()=>{needsRender=true;});
const annotationLayer=$('#annotation-layer');let highlight=null;
function dispose(group){group?.traverse(o=>{o.geometry?.dispose();});}
function addAnnotation(text,x,y,dim=false,z=30){const el=document.createElement('div');el.className='annotation'+(dim?' dim':'');el.textContent=text;annotationLayer.append(el);annotations.push({el,p:new THREE.Vector3(mm(x),mm(z),mm(y))});}
function serviceZone(o){const angle=(o.rotation||0)*Math.PI/180;const f=['north','east','south','west'][(['north','east','south','west'].indexOf(o.front||'south')+Math.round((o.rotation||0)/90))%4];if(o.rotation){const w=Math.abs(o.width*Math.cos(angle))+Math.abs(o.depth*Math.sin(angle)),d=Math.abs(o.width*Math.sin(angle))+Math.abs(o.depth*Math.cos(angle));o={...o,x:o.x+o.width/2-w/2,y:o.y+o.depth/2-d/2,width:w,depth:d};}let reach=['fridge','dishwasher','washer','hob'].includes(o.type)?650:['chair','stool'].includes(o.type)?300:600;
 if(o.type==='bed'||['upper','tv','mirror','shower','shelf'].includes(o.type))return null;
 if(['chair','stool'].includes(o.type))return{x:o.x-50,y:o.y-50,width:o.width+100,depth:o.depth+100,label:'Стул + резерв движения'};
 const zone={id:o.id+'-use',x:o.x,y:o.y,width:o.width,depth:o.depth,label:o.opening==='sliding'?'Доступ к купе':'Открывание / использование'};
 if(f==='south'){zone.y+=o.depth;zone.depth=reach;}if(f==='north'){zone.y-=reach;zone.depth=reach;}if(f==='east'){zone.x+=o.width;zone.width=reach;}if(f==='west'){zone.x-=reach;zone.width=reach;}return zone;}
function rebuild(){needsRender=true;if(root){scene.remove(root);dispose(root);}root=new THREE.Group();root.name='MASTER_APARTMENT_'+layout.id;scene.add(root);const plan=state.mode==='plan';renderer.shadowMap.enabled=!plan;lighting.children[1].castShadow=!plan;for(const mat of Object.values(mats))mat.needsUpdate=true;if(state.focus&&!plan){const studio=createStudio(geometry,layout,mats,state.focus);studio.getObjectByName('WALLS').visible=state.walls;studio.getObjectByName('FURNITURE_'+layout.id).visible=state.furniture;root.add(studio);obstacles=colliders(geometry,layout,{furniture:state.furniture,doorsOpen:state.doors});annotations=[];annotationLayer.replaceChildren();selectObject(state.selected);updateUI();return;}root.add(createArchitecture(geometry,layout,mats,{cut:state.cut,plan,walls:state.walls,doorsOpen:state.doors}));
 const furniture=new THREE.Group();furniture.name='FURNITURE_'+layout.id;furniture.visible=state.furniture;root.add(furniture);for(const o of layout.furniture){if(plan&&(o.elevation||0)>1200)continue;const obj=createFurniture(o,mats);furniture.add(obj);}
 const decor=createDecor(layout,mats);decor.visible=!plan;root.add(decor);
 const anno=new THREE.Group();anno.name='ANNOTATIONS';root.add(anno);annotations=[];annotationLayer.replaceChildren();
 if(state.labels&&state.mode!=='walk'){for(const r of layout.rooms){addAnnotation(r.name+(r.area?' · '+r.area.toFixed(1)+' м²':''),r.x,r.y,false,50);}}
 if(state.dimensions&&state.mode!=='walk'){dimensionLine(anno,[0,-420],[6400,-420]);addAnnotation('6400',3200,-450,true);dimensionLine(anno,[-430,0],[-430,8300]);addAnnotation('8300*',-430,4050,true);dimensionLine(anno,[6820,0],[6820,7440]);addAnnotation('7440*',6820,3700,true);for(const c of layout.clearances){const from=[c.x-(c.axis==='x'?c.length/2:0),c.y-(c.axis==='y'?c.length/2:0)],to=[c.x+(c.axis==='x'?c.length/2:0),c.y+(c.axis==='y'?c.length/2:0)];dimensionLine(anno,from,to);addAnnotation(c.value+' мм',c.x,c.y,true,55);}}
 if(state.zones){for(const o of layout.furniture){const z=serviceZone(o);if(!z)continue;const mat=new THREE.MeshBasicMaterial({color:0x8ea990,transparent:true,opacity:.16,depthWrite:false,side:THREE.DoubleSide});box(anno,mat,z.x,z.y,z.width,z.depth,8,20);const pts=[[z.x,z.y],[z.x+z.width,z.y],[z.x+z.width,z.y+z.depth],[z.x,z.y+z.depth],[z.x,z.y]];for(let i=1;i<pts.length;i++)dimensionLine(anno,pts[i-1],pts[i],0x789479);}
 for(const d of layout.doors){if(d.mechanism?.includes('sliding'))continue;let hinge,theta0,theta1;if(d.hinge){hinge=d.hinge;theta0=d.arcStart*Math.PI/180;theta1=d.arcEnd*Math.PI/180;}else if(d.axis==='x'){hinge=[d.x,d.swing==='outward'?d.y:d.y+120];theta0=0;theta1=d.swing==='outward'?-Math.PI/2:Math.PI/2;}else{hinge=[d.x+120,d.y+d.width];theta0=-Math.PI/2;theta1=0;}const p=[];for(let i=0;i<=24;i++){const t=theta0+(theta1-theta0)*i/24;p.push([hinge[0]+Math.cos(t)*d.width,hinge[1]+Math.sin(t)*d.width]);}for(let i=1;i<p.length;i++)dimensionLine(anno,p[i-1],p[i],0xad9d74);}}
 obstacles=colliders(geometry,layout,{furniture:state.furniture,doorsOpen:state.doors});if(state.applianceOpen&&state.furniture){const item=layout.furniture.find(o=>o.id===state.applianceOpen);const leaf=item&&openingLeaf(item);if(leaf){box(root,mats.joinery,leaf.x,leaf.y,leaf.width,leaf.depth,leaf.height,leaf.elevation,leaf.id);obstacles.push(leaf);}}selectObject(state.selected);updateUI();}
function selectObject(id){needsRender=true;if(highlight){scene.remove(highlight);highlight.geometry?.dispose();highlight=null;}state.selected=id;const o=layout.furniture.find(o=>o.id===id);if(!o){$('#selection').innerHTML='<span class="eyebrow">ОБЪЕКТЫ В МАСШТАБЕ</span><p>Нажмите на мебель,<br>чтобы увидеть её размеры.</p>';return;}
 const selectedGroup=root.getObjectByName('FURNITURE_'+layout.id)?.getObjectByName(id);const bounds=selectedGroup?new THREE.Box3().setFromObject(selectedGroup):new THREE.Box3();highlight=new THREE.Box3Helper(bounds,0x608769);scene.add(highlight);
 $('#selection').innerHTML='<span class="eyebrow">'+roomNames[o.room]+'</span><strong>'+o.label+'</strong><div class="dimensions">'+o.width+' × '+o.depth+' × '+o.height+'</div><p>Габарит Ш × Г × В, мм<br>x '+o.x+' · y '+o.y+(o.mattress?'<br>Матрас '+o.mattress.join(' × '):'')+'</p>'+(openingLeaf(o)?'<button id="open-appliance">'+(state.applianceOpen===id?'Закрыть дверцу':'Проверить открытую дверцу')+'</button>':'');if($('#open-appliance'))$('#open-appliance').onclick=()=>{state.applianceOpen=state.applianceOpen===id?null:id;rebuild();toast('Показан условный габарит дверцы. Точную фурнитуру уточним по технике.');};}
function setMode(mode){state.focus=null;state.mode=mode;if(mode==='walk'){state.cut=false;state.walls=true;state.doors=true;$('#cut').checked=false;$('#walls').checked=true;$('#doors').checked=true;}else if(state.mode==='plan')state.dimensions=true;cameras.setMode(mode);rebuild();if(mode==='walk')cameras.teleport(layout.routes.entry);}
function setVariant(id){state.focus=null;layout=layouts.find(v=>v.id===id)||layouts[0];state.variant=layout.id;state.selected=null;state.applianceOpen=null;cameras.setMode(state.mode);rebuild();if(state.mode==='walk')cameras.teleport(layout.routes.entry);}
function setStyle(id){const style=interiorStyles.find(v=>v.id===id);if(!style)return;const previous=mats;mats=materials(style);state.style=id;scene.background.set(style.background);ground.material.color.set(style.background);renderer.toneMappingExposure=style.exposure;lighting.children[0].color.set(style.light);lighting.children[1].color.set(style.light);rebuild();disposeMaterials(previous);}
function updateUI(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));document.querySelectorAll('.variant').forEach(b=>{b.classList.toggle('active',b.dataset.variant===layout.id);b.setAttribute('aria-pressed',String(b.dataset.variant===layout.id));});document.querySelectorAll('[data-style]').forEach(b=>{b.classList.toggle('active',b.dataset.style===state.style);b.setAttribute('aria-pressed',String(b.dataset.style===state.style));});$('#variant-caption').textContent=layout.id+' / '+layout.name.toUpperCase();$('#view-caption').textContent=(state.focus?'Интерьер · '+(roomNames[state.focus]||state.focus)+' · разрез':({iso:'Изометрия',orbit:'Свободное вращение',plan:'Ортографический план',top:'Вид сверху · перспектива',perspective:'Перспектива',walk:'Прогулка · '+cameras.eye+' мм'})[state.mode]+(state.mode!=='walk'&&state.cut?' · срез стен':''));$('#walk-panel').hidden=state.mode!=='walk';$('#canvas-help').hidden=state.mode==='walk';$('#layout-summary').textContent=layout.subtitle+' · 2 комнаты · требуется обмер';for(const k of['furniture','walls','cut','labels','dimensions','zones','doors'])$('#'+k).checked=state[k];}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4000);}
$('#variants').innerHTML=layouts.map(v=>'<button class="variant" data-variant="'+v.id+'" aria-pressed="false"><span class="variant-letter">'+v.id+'</span><span><strong>'+v.name+(v.id==='D'?'<span class="tag">БАЗА</span>':'')+'</strong><small>'+v.subtitle+'</small></span></button>').join('');
$('#styles').innerHTML=interiorStyles.map(s=>'<button class="style-option" data-style="'+s.id+'" aria-pressed="false"><span class="style-swatches"><i style="background:'+s.floor+'"></i><i style="background:'+s.sofa+'"></i><i style="background:'+s.stone+'"></i></span><span><strong>'+s.number+' · '+s.name+'</strong><small>'+s.tagline+'</small></span></button>').join('');$('#styles').onclick=e=>{const b=e.target.closest('[data-style]');if(b)setStyle(b.dataset.style);};$('#variants').onclick=e=>{const b=e.target.closest('[data-variant]');if(b)setVariant(b.dataset.variant);};$('#modes').onclick=e=>{const b=e.target.closest('[data-mode]');if(b)setMode(b.dataset.mode);};$('#reset').onclick=()=>{if(state.focus)viewRoom(state.focus);else cameras.setMode(state.mode);selectObject(null);};for(const k of['furniture','walls','cut','labels','dimensions','zones','doors'])$('#'+k).onchange=e=>{state[k]=e.target.checked;rebuild();if(state.mode==='walk'&&!canStand(cameras.camera.position.x*1000,cameras.camera.position.z*1000,geometry,obstacles,250)){cameras.teleport(layout.routes.entry);toast('Положение камеры сброшено ко входу, чтобы избежать пересечения.');}};
const raycaster=new THREE.Raycaster();let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||state.mode==='walk')return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),cameras.camera);const hit=raycaster.intersectObjects(root.children,true).find(h=>h.object.userData.id&&layout.furniture.some(o=>o.id===h.object.userData.id));selectObject(hit?.object.userData.id||null);});
const referenceViews={adult:{pos:[5.4,6.4,10.2],target:[1.6,.4,6.4],walk:[2750,5200],look:[2100,6500]},alice:{pos:[8.2,6.2,9.2],target:[4.9,.4,5.6],walk:[4450,4050],look:[5350,5500]},kitchen:{pos:[6.8,5.7,6.3],target:[1.2,.5,1.2],walk:[1400,1100],look:[600,700]},living:{pos:[5.2,5,6.6],target:[1.6,.3,3.4],walk:[1150,3550],look:[2000,3550]},bath:{pos:[6.5,4.8,4.2],target:[3.6,.4,1.0],walk:[3540,1150],look:[3500,200]}};
function viewRoom(name){if(name==='all'){state.focus=null;setMode('iso');return;}const v=referenceViews[name];if(state.mode==='walk'){if(!cameras.teleport(v.walk,v.look))toast('Эта точка занята в варианте '+layout.id+'. Начните прогулку от входа.');}else{state.mode='perspective';state.focus=name;const spec=roomSpec(layout,name);cameras.view(spec.pos,spec.target);rebuild();}}
$('#rooms').onclick=e=>{const b=e.target.closest('[data-room]');if(b)viewRoom(b.dataset.room);};document.querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{cameras.setEye(Number(b.dataset.eye));document.querySelectorAll('[data-eye]').forEach(c=>c.classList.toggle('active',c===b));updateUI();});document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{cameras.keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>cameras.keys.delete(b.dataset.key);});
const routeNames={entry:'Вход',storage:'Хранение',kitchen:'Кухня',bar:'Обеденный стол',adult:'Ваша спальня',alice:'Вторая комната',adultBed:'Кровать',adultWardrobe:'Шкаф',aliceBed:'Вторая кровать',aliceDesk:'Рабочий стол',childShelf:'Книжный шкаф',bathroom:'Санузел',fridge:'Холодильник',dishwasher:'ПММ',sofa:'Диван',bathBasin:'Раковина',bathToilet:'Унитаз',bathWasher:'Стиральная машина',bathTub:'Ванна'};
function routeResult(a,b){return findRoute(layout.routes[a],layout.routes[b],geometry,colliders(geometry,layout),{radius:250});}
function startRoute(a,b){const res=routeResult(a,b);if(!res.ok){toast('Маршрут не найден: '+res.reason);return res;}state.applianceOpen=null;setMode('walk');cameras.teleport(res.path[0]);cameras.route=res.path.slice(1);$('#details').close();toast(routeNames[a]+' → '+routeNames[b]+' · '+(res.lengthMm/1000).toFixed(1)+' м');return res;}
function modal(html){$('#dialog-content').innerHTML=html;$('#details').showModal();}
$('#close-dialog').onclick=()=>$('#details').close();$('#details').addEventListener('click',e=>{if(e.target===$('#details'))$('#details').close();});
function showAssumptions(){modal('<h2>Размеры с оговорками.</h2><p>Главная ширина <b>6400 мм</b> взята из цепочки 3175 + 250 + 2975. Вертикали и окна на исходном изображении противоречивы: модель — проверяемая гипотеза, а не подтверждённый обмер. *Площадь контура '+(polygonArea(geometry.floor)/1e6).toFixed(2)+' м² — результат этой гипотезы, в описании округлена до «около 50 м²».</p>'+geometry.assumptions.map(a=>'<div class="assumption"><b>'+a.id+'</b><p>'+a.text+'</p></div>').join('')+'<p class="small">Вход сверху справа. Окна снизу. Север по плану неизвестен. Схема новых перегородок не означает согласование перепланировки.</p><div class="export-row"><button id="data-download">Скачать данные модели JSON</button><a href="geometry-notes.md" target="_blank">Разбор обмерного плана ↗</a></div>');$('#data-download').onclick=()=>downloadJSON();}
$('#assumptions').onclick=showAssumptions;
$('#report').onclick=()=>{modal('<h2>Пять разных планировок на одной коробке.</h2><p>База — <b>D «Лиза»</b>. E–H меняют положение перегородок, дверей и мебели, сохраняя кухню слева, центральную ванную и две комнаты у окон. План H также расширяет ванную и требует отдельной инженерной проверки.</p><p>Пять материалов и цветов можно примерить к каждой расстановке. Прогулка проверяет геометрию для тела Ø500 мм, а не гарантирует универсальный комфорт.</p><p>Откройте «План» и включите размеры; нажмите на предмет, чтобы увидеть габарит. «Решения и проходы» объясняет выбор и запускает маршруты. PNG сохраняет вид, GLB — объёмную модель.</p><div class="export-row"><a href="LIZA.html" target="_blank">План, размеры и объяснения ↗</a><button id="data-download">Скачать JSON</button></div><p class="small">Размеры коробки и окон остаются условными; места коммуникаций неизвестны. Перед стройкой нужны обмер и инженерная привязка.</p>');$('#data-download').onclick=downloadJSON;};
$('#compare').onclick=()=>{
 const current=layout.id==='D';
 modal('<h2>'+layout.id+' · '+layout.name+'</h2><p>'+layout.subtitle+'</p><h3>Почему так</h3><ul>'+layout.pros.map(t=>'<li>'+t+'</li>').join('')+'</ul><h3>Размеры этого варианта</h3><div class="table-wrap"><table><tr><th>Участок</th><th>Размер</th></tr>'+layout.clearances.map(c=>'<tr><td>'+c.label+'</td><td>'+c.value+' мм</td></tr>').join('')+'</table></div><h3>Что учитывать</h3><ul>'+layout.cons.map(t=>'<li>'+t+'</li>').join('')+'</ul>'+(current?'<p>В зоне перехода к кухне остаётся компактное место между ванной и диваном. Обеденный стол — на двоих. Размеры дверей относятся к проёмам до коробок.</p><p><a href="LIZA.html" target="_blank">Подробный план и решения ↗</a></p>':'')+'<h3>Пройти по квартире</h3><p class="small">Сетка 75 мм, тело Ø500 мм, двери открыты. Это проверка достижимости; она не заменяет проверку удобства. Нажмите маршрут для прогулки.</p><div class="route-grid">'+layout.routePairs.map(([a,b])=>{const r=routeResult(a,b);return '<button data-route="'+a+','+b+'">'+(r.ok?'✓ ':'! ')+routeNames[a]+' → '+routeNames[b]+(r.ok?' · '+(r.lengthMm/1000).toFixed(1)+' м':' · нет прохода')+'</button>';}).join('')+'</div>');
 document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>startRoute(...b.dataset.route.split(',')));
};
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
function downloadJSON(){download(new Blob([JSON.stringify({project,geometry,layouts,selectedLayout:layout.id},null,2)],{type:'application/json'}),'MASTER-APARTMENT.json');}
function exportModel(){const exportRoot=new THREE.Group();exportRoot.name='MASTER_APARTMENT_'+layout.id;exportRoot.userData={units:'meters',sourceDataUnits:'mm',layout:layout.id,approvalStatus:project.approvalStatus};exportRoot.add(createArchitecture(geometry,layout,mats,{cut:false,plan:false,walls:true,doorsOpen:true}));for(const o of layout.furniture)exportRoot.add(createFurniture(o,mats));exportRoot.add(createDecor(layout,mats));return new Promise((resolve,reject)=>new GLTFExporter().parse(exportRoot,resolve,reject,{binary:true,onlyVisible:true}));}
$('#export').onclick=async()=>{try{download(new Blob([await exportModel()],{type:'model/gltf-binary'}),'MASTER-'+layout.id+'.glb');toast('Полная модель '+layout.id+' сохранена.');}catch(e){toast('Ошибка экспорта: '+e.message);}};
$('#snapshot').onclick=()=>{renderer.render(scene,cameras.camera);renderer.domElement.toBlob(blob=>download(blob,'apartment-'+layout.id+'-'+state.mode+'.png'));};
new ResizeObserver(()=>{needsRender=true;const {width,height}=$('#canvas-container').getBoundingClientRect();renderer.setSize(width,height);cameras.resize(width,height);}).observe($('#canvas-container'));
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);cameras.tick(clock.getDelta());if(!needsRender&&state.mode!=='walk')return;needsRender=false;for(const a of annotations){const p=a.p.clone().project(cameras.camera);a.el.style.left=(p.x*.5+.5)*renderer.domElement.clientWidth+'px';a.el.style.top=(-p.y*.5+.5)*renderer.domElement.clientHeight+'px';a.el.style.display=p.z<1&&p.z>-1?'':'none';}renderer.render(scene,cameras.camera);}rebuild();animate();const initialRoom=new URLSearchParams(location.search).get('room');if(['adult','alice','kitchen','living','bath'].includes(initialRoom))viewRoom(initialRoom);
window.apartment={state,geometry,layouts,project,interiorStyles,setStyle,get layout(){return layout},get camera(){return cameras.camera},get renderer(){return renderer},cameras,setVariant,setMode,viewRoom,rebuild,selectObject,routeResult,startRoute,canStand:(x,y)=>canStand(x,y,geometry,obstacles,250),setLayer:(key,v)=>{state[key]=v;rebuild();},exportModel,serviceZone,render:()=>renderer.render(scene,cameras.camera),ready:true};

}
main().catch(console.error);
